apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apache
  name: apache
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: project-app
          image: httpd:latest
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/local/apache2/htdocs
              name: apache-cm0
        - name: apache-exporter
          image: lusotycoon/apache-exporter:latest
          args:
            - --scrape_uri=http://localhost/server-status?auto
          ports:
            - containerPort: 9117
              name: metrics
      restartPolicy: Always
      volumes:
        - configMap:
            name: apache-cm0
          name: apache-cm0
