apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: apache
    app: apache
  name: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: apache
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: apache
        app: apache
    spec:
      containers:
        - image: httpd:latest
          name: project-app
          ports:
            - containerPort: 80
              protocol: TCP 
          volumeMounts:
            - mountPath: /usr/local/apache2/htdocs
              name: apache-cm0
        - name: apache-exporter
          image: lusotycoon/apache-exporter:latest
          args:
          - --scrape_uri=http://localhost/server-status?auto
          ports:
          - containerPort: 9117
            name: metrics
      restartPolicy: Always
      volumes:
        - configMap:
            name: apache-cm0
          name: apache-cm0
