apiVersion: v1
data:
  index.html: " <!DOCTYPE html>\n<html>\n<body>\n\n<h1>My First Heading</h1>\n<p>My first paragraph.</p>\n\n</body>\n</html> \n"
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: apache
  name: apache-cm0
